# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 047583b59b883cbaf46edba974823ce41a7e462992382e8673981d43c13c6affd8f85b86220ea77e62ef012560ac45e508c720129bc0490bba7a42bfcf69f7b4

test:
  secret_key_base: 8b0275f643500745b15eaf605bf662f9851f3bbcd287120777524ff0ee99a4b314cec09291acc168030c3ed088328209ead2c091ba48c2801316cb55f87013f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
